---
server:
  port: 8081
  contextPath: /SpringBootCRUDApp
---
spring:
  profiles: postgresql
datasource:
  sampleapp:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 78320
    driverClassName: org.postgresql.Driver
    defaultSchema: public
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  profiles: local,default
datasource:
  sampleapp:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
    defaultSchema: public
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  profiles: oracle
datasource:
  sampleapp:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: czhang
    password: 78320
    driverClassName: jdbc.driver.OracleDriver
    defaultSchema: czhang
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.Oracle10gDialect
---
spring:
  profiles: test
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password: 
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: mysql
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/websystique
    username: root
    password: 78320
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

